return {
  -- {
  --   "kiddos/gemini.nvim",
  --   opts = {},
  -- },
  -- {
  --   "zbirenbaum/copilot.lua",
  --   config = function()
  --     require("copilot").setup({})
  --   end,
  -- },
  -- {
  --   "zbirenbaum/copilot-cmp",
  --   opts = {},
  --   config = function(_, opts)
  --     local copilot_cmp = require("copilot_cmp")
  --     copilot_cmp.setup(opts)
  --     -- lazyvim.lsp.on_attach(function()
  --     --   copilot_cmp._on_insert_enter({})
  --     -- end, "copilot")
  --   end,
  --   specs = {
  --     {
  --       "hrsh7th/nvim-cmp",
  --       optional = true,
  --       ---@param opts cmp.configschema
  --       opts = function(_, opts)
  --         table.insert(opts.sources, 1, {
  --           name = "copilot",
  --           group_index = 1,
  --           priority = 100,
  --         })
  --       end,
  --     },
  --   },
  -- },
  -- {
  --   "copilotc-nvim/copilotchat.nvim",
  --   dependencies = {
  --     { "zbirenbaum/copilot.lua" }, -- or zbirenbaum/copilot.lua
  --     { "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
  --   },
  --   build = "make tiktoken", -- only on macos or linux
  --   opts = {
  --     model = "gpt-4.1",
  --     temperature = 0.5,
  --   },
  --   headers = {
  --     user = "👤 You: ",
  --     assistant = "🤖 Copilot: ",
  --     tool = "🔧 Tool: ",
  --   },
  --   separator = "━━",
  --   show_folds = false,
  --   keys = {
  --     { "cp", "<cmd>CopilotChat<cr>", desc = "Copilot Chat" },
  --   },
  --   -- see commands section for default commands if you want to lazy load on them
  -- },
}
